config/routes.rb
JasonHall::Application.routes.draw do
  resources :partners
  devise_for :admins

  root 'home#index'

  get "/reviews", to: 'review#index'
  get "/blog", to: 'blog#index'
  get "/resources", to: 'resources#index'
  get "/home", to: 'home#index'
  get "/blog/new"
  get "/blog/comments"
  get "/category", to: 'partners#category'
  get '/contact', to: 'contact#index'
  get '/tools', to: 'tools#index'
  get '/amortization_content', to: 'tools#amortization_content'

  post '/new_program', to: 'resources#new_program'
  post '/edit_program', to: 'resources#edit_program'
  post '/new_process', to: 'resources#new_process'
  post '/edit_process', to: 'resources#edit_process'
  post '/resources/swap', to: 'resources#swap'
  post '/new_question', to: 'resources#new_question'
  post '/edit_question', to: 'resources#edit_question'
  post '/resources/swap_question', to: 'resources#swap_question'
  post '/blog/approve'
  post '/blog/new_comment'
  post '/blog/new_post'
  post '/blog/edit'
  post '/blog/approve_comment'
  post '/blog/delete_comment'
  post '/blog/delete_post'
  post '/new_partner', to: 'partners#new_partner'
  post '/edit_partner', to: 'partners#edit_partner'
  post '/send_feedback', to: 'contact#send_feedback'
  post '/calculate_amortization', to: 'tools#calculate_amortization'
  post '/text_review', to: 'review#text_review'
  post '/video_review', to: 'review#video_review'
  post '/approve_text_review', to: 'review#approve_text_review'
  post '/remove_text_review', to: 'review#remove_text_review'
  post '/add_video', to: 'review#add_video'
  post '/delete_video', to: 'review#delete_video'
  post '/add_review', to: 'review#add_review'

  patch '/blog/edit_post/:id', to: 'blog#edit_post'

  delete '/delete_program', to: 'resources#delete_program'
  delete '/delete_process', to: 'resources#delete_process'
  delete '/delete_question', to: 'resources#delete_question'
end

app/views/resources/_edit_process_modal.html.haml
#edit_process_modal.modal.fade{role: 'dialog', 'aria-labelledby' => 'edit_process_label', 'aria-hidden' => 'true'}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{type: 'button', 'data-dismiss' => 'modal'}
          %span{'aria-hidden' => 'true'} &times;
        %h4 Edit Step
      .modal-body
        #edit_process_modal_error
        %form#edit_process_form{role: 'form', name: 'edit_process', action: 'edit_process', method: 'post'}
          = hidden_field_tag :authenticity_token, form_authenticity_token
          %input#edit_process_id.hidden{name: 'id'}
          .form-group
            %label.control-label{'for' => 'edit_step_name'}  Step Name
            %input#edit_step_name.form-control{name: 'edit_step_name', type: 'text', placeholder: 'i.e. Pre-Qualification'}
          .form-group
            %label.control-label{'for' => 'step_description'}  Description
            %textarea#edit_step_description.form-control{name: 'description', rows: '3'}
          .form-group
            %button.btn.btn-default{'data-dismiss' => 'modal'} Close
            %button#edit_modal.btn.btn-primary{type: 'submit'} Save

app/views/resources/_edit_program_modal.html.haml
#edit_program_modal.modal.fade{role: 'dialog', 'aria-labelledby' => 'edit_program_label', 'aria-hidden' => 'true'}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{type: 'button', 'data-dismiss' => 'modal'}
          %span{'aria-hidden' => 'true'} &times;
        %h4 Edit Program
      .modal-body
        #edit_modal_error
        %form#edit_program_form{role: 'form', name: 'edit_program', action: 'edit_program', method: 'post'}
          = hidden_field_tag :authenticity_token, form_authenticity_token
          %input#edit_id.hidden{name: 'id'}
          .form-group
            %label.control-label{'for' => 'type'}  Loan Type
            %input#type.form-control{name: 'loan_type', type: 'text', placeholder: 'i.e. Conventional, FHA, VA'}
          .form-group
            %label.control-label{'for' => 'description'}  Description
            %textarea#description.form-control{name: 'description', rows: '3'}
          .form-group
            %button.btn.btn-default{'data-dismiss' => 'modal'} Close
            %button#edit_modal.btn.btn-primary{type: 'submit'} Save

app/views/resources/_edit_question_modal.html.haml
#edit_question_modal.modal.fade{role: 'dialog', 'aria-labelledby' => 'edit_question_label', 'aria-hidden' => 'true'}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{type: 'button', 'data-dismiss' => 'modal'}
          %span{'aria-hidden' => 'true'} &times;
        %h4 Edit Question
      .modal-body
        #edit_question_modal_error
        %form#edit_question_form{role: 'form', name: 'edit_question', action: 'edit_question', method: 'post'}
          = hidden_field_tag :authenticity_token, form_authenticity_token
          %input#edit_question_id.hidden{name: 'id'}
          .form-group
            %label.control-label{'for' => 'edit_question'}  Question
            %input#edit_question.form-control{name: 'edit_question', type: 'text', placeholder: 'i.e. How do I apply?'}
          .form-group
            %label.control-label{'for' => 'edit_answer'}  Answer
            %textarea#edit_answer.form-control{name: 'description', rows: '3'}
          .form-group
            %button.btn.btn-default{'data-dismiss' => 'modal'} Close
            %button.btn.btn-primary{type: 'submit'} Save

app/views/resources/_faq_accordion.html.haml
#faq_accordion.panel-group{"aria-multiselectable" => "true", :role => "tablist"}
  - questions.each_with_index do |p, i|
    - id = "faq_#{p.id}"
    - order = p.question_number
    - collapse = "#{id}_collapse"
    - display = i == 0 ? 'in' : 'out'
    .panel.panel-default
      .panel-heading.question-panel-heading{:role => "tab", id: id, 'data-order' => order, 'data-toggle' => 'collapse', 'data-parent' => '#faq_accordion', :href => "##{collapse}"}
        %h4.panel-title
          %a.question-text{"aria-controls" => collapse, "aria-expanded" => "true", "data-parent" => "#faq_accordion", "data-toggle" => "collapse", :href => "##{collapse}"}
            = p.question
          - if admin_signed_in?
            .admin-control.pull-right
              - if order == 1
                - up_class = 'inactive'
              - else
                - up_class = 'complimentary'
              - if order == questions.count
                - down_class = 'inactive'
              - else
                - down_class = 'complimentary'
              = fa_icon 'arrow-up', class: "right-20 pointer question-up #{up_class}"
              = fa_icon 'arrow-down', class: "right-20 pointer question-down #{down_class}"
              = link_to '#edit_question_modal', class: 'edit-question', 'data-toggle' => 'modal' do
                = fa_icon 'edit', class: 'white right-20 pointer'
              = link_to(delete_question_path(id: p.id), data: { confirm: "Are you sure you want to delete: #{p.question}" },class: 'delete-question', method: :delete) do
                = fa_icon 'trash', class: 'white right-20 pointer'
      .panel-collapse.collapse{"aria-labelledby" => id, :role => "tabpanel", id: collapse, class: display}
        .panel-body
          .panel-text
            = p.answer

app/views/resources/_loan_faq.html.haml
- if admin_signed_in?
  .add-question.center.top-10-bottom-10
    %a#add_question.complimentary{href: '#'}
      = fa_icon 'plus', text: 'Add Question'
    .new-question
      %form#new_question_form{role: 'form', name: 'new_question', action: 'new_question', method: 'post'}
        = hidden_field_tag :authenticity_token, form_authenticity_token
        .form-group
          %label.control-label{'for' => 'question'}  Question
          %input#question.form-control{name: 'question', type: 'text', placeholder: 'i.e. How do I apply?'}
        .form-group
          %label.control-label{'for' => 'answer'}  Answer
          %textarea#answer.form-control{name: 'answer', rows: '3'}
        .form-group
          %label.control-label{'for' => 'question_order'} Question #:
          %select#question_order.form-control{name: 'question_order'}
            - count = @questions.blank? ? 0 : @questions.count
            - if count == 0
              %option 1
            - else
              - 1.upto(count + 1) do |i|
                %option
                  = i
        .form-group
          %button#add_question_button.add-button.btn.gradient{type: 'submit'} Save
.questions
  = render partial: '/resources/faq_accordion', locals: { questions: @questions }
= render partial: '/resources/edit_question_modal'

app/views/resources/_loan_process.html.haml
- if admin_signed_in?
  .add-process.center.top-10-bottom-10
    %a#add_process.complimentary{href: '#'}
      = fa_icon 'plus', text: 'Add new step'
    .new-process
      %form#new_process_form{role: 'form', name: 'new_process', action: 'new_process', method: 'post'}
        = hidden_field_tag :authenticity_token, form_authenticity_token
        .form-group
          %label.control-label{'for' => 'step_name'}  Step Title
          %input#step_name.form-control{name: 'step_name', type: 'text', placeholder: 'i.e. Pre-Qualification'}
        .form-group
          %label.control-label{'for' => 'step_description'}  Description
          %textarea#step_description.form-control{name: 'description', rows: '3'}
        .form-group
          %label.control-label{'for' => 'step_order'} Step #:
          %select#step_order.form-control{name: 'step_order'}
            - count = @steps.blank? ? 0 : @steps.count
            - if count == 0
              %option 1
            - else
              - 1.upto(count + 1) do |i|
                %option
                  = i
        .form-group
          %button#add_process_button.add-button.btn.gradient{type: 'submit'} Save
.loan-process
  = render partial: '/resources/loan_process_accordion', locals: { steps: @steps }
= render partial: '/resources/edit_process_modal'

app/views/resources/_loan_process_accordion.html.haml
#process_accordion.panel-group{"aria-multiselectable" => "true", :role => "tablist"}
  - steps.each_with_index do |p, i|
    - id = "loan_process_#{p.id}"
    - order = p.step_number
    - collapse = "#{id}_collapse"
    - display = i == 0 ? 'in' : 'out'
    .panel.panel-default
      .panel-heading.process-panel-heading{:role => "tab", id: id, 'data-order' => order, 'data-toggle' => 'collapse', 'data-parent' => '#process_accordion', :href => "##{collapse}"}
        %h4.panel-title
          %a.step-text{"aria-controls" => collapse, "aria-expanded" => "true", "data-parent" => "#process_accordion", "data-toggle" => "collapse", :href => "##{collapse}"}
            = "Step #{order}: #{p.name}"
          - if admin_signed_in?
            .admin-control.pull-right
              - if order == 1
                - up_class = 'inactive'
              - else
                - up_class = 'complimentary'
              - if order == steps.count
                - down_class = 'inactive'
              - else
                - down_class = 'complimentary'
              = fa_icon 'arrow-up', class: "right-20 pointer process-up #{up_class}"
              = fa_icon 'arrow-down', class: "right-20 pointer process-down #{down_class}"
              = link_to '#edit_process_modal', class: 'edit-process', 'data-toggle' => 'modal' do
                = fa_icon 'edit', class: 'white right-20 pointer'
              = link_to(delete_process_path(id: p.id), data: { confirm: "Are you sure you want to delete: #{p.name}?" },class: 'delete-process', method: :delete) do
                = fa_icon 'trash', class: 'white right-20 pointer'
      .panel-collapse.collapse{"aria-labelledby" => id, :role => "tabpanel", id: collapse, class: display}
        .panel-body
          .panel-text
            = p.description

app/views/resources/_loan_program_accordion.html.haml
.programs-container
  #program_accordion.panel-group{"aria-multiselectable" => "true", :role => "tablist"}
    - programs.each_with_index do |p, i|
      - id = "loan_program_#{p.id}"
      - collapse = "#{id}_collapse"
      - display = i == 0 ? 'in' : 'out'
      .panel.panel-default
        .panel-heading.program-panel-heading{:role => "tab", id: id, 'data-toggle' => 'collapse', 'data-parent' => '#program_accordion', :href => "##{collapse}"}
          %h4.panel-title
            %a.loan-text{"aria-controls" => collapse, "aria-expanded" => "true", "data-parent" => "#program_accordion", "data-toggle" => "collapse", :href => "##{collapse}"}
              = p.loan_type
            - if admin_signed_in?
              .admin-control.pull-right
                = link_to '#edit_program_modal', class: 'edit-program', 'data-toggle' => 'modal' do
                  = fa_icon 'edit', class: 'white right-20 pointer'
                = link_to(delete_program_path(id: p.id), data: { confirm: "Are you sure you want to delete: #{p.loan_type}?" },class: 'delete-program', method: :delete) do
                  = fa_icon 'trash', class: 'white right-20 pointer'
        .panel-collapse.collapse{"aria-labelledby" => id, :role => "tabpanel", id: collapse, class: display}
          .panel-body
            .panel-text
              = p.description

app/views/resources/_loan_programs.html.haml
- if admin_signed_in?
  .add-program.center.top-10-bottom-10
    %a#add_program.add-button.complimentary{href: '#'}
      = fa_icon 'plus', text: 'Add New Program'
    .new-program
      %form#new_program_form{role: 'form', name: 'new_program', action: 'new_program', method: 'post'}
        = hidden_field_tag :authenticity_token, form_authenticity_token
        .form-group
          %label.control-label{'for' => 'loan_type'}  Loan Type
          %input#loan_type.form-control{name: 'loan_type', type: 'text', placeholder: 'i.e. Conventional, FHA, VA'}
        .form-group
          %label.control-label{'for' => 'loan_description'}  Description
          %textarea#loan_description.form-control{name: 'description', rows: '3'}
        .form-group
          %button#add_new_button.add-button.btn.gradient{type: 'submit'} Save
= render partial: '/resources/loan_program_accordion', locals: { programs: @programs }
= render partial: '/resources/edit_program_modal'

app/views/resources/index.html.haml
#alert
  - tab = params['tab'].nil? ? 'programs' : params['tab']
.col-xs-12.col-md-4.bottom-thirty
  %br
  .text-center
    %h4.white Loan Steps
    .help-text.white Hover to reveal
    %hr
  .circle-reveal.pointer
    .circle 1
    .text-center.reveal.hide
      .lead.white Get Pre-qualified
      %hr
  .circle-reveal.pointer
    .circle 2
    .text-center.reveal.hide
      %hr
      .lead.white Complete Application
      %hr
  .circle-reveal.pointer
    .circle 3
    .text-center.reveal.hide
      %hr
      .lead.white Obtain Approval
      %hr
  .circle-reveal.pointer
    .circle 4
    .text-center.reveal.hide
      %hr
      .lead.white Live
      %hr
.col-xs-12.col-md-8.bottom-thirty
  %ul#resource_tabs.nav.nav-tabs{role: 'tablist'}
    - first_active = (tab == 'programs') ? 'active' : 'not-active'
    %li{role: 'presentation', class: first_active}
      %a{'data-toggle' => 'tab', href: '#programs', role: 'tab'}
        Loan Programs
    - second_active = (tab == 'process') ? 'active' : 'not-active'
    %li{role: 'presentation', class: second_active}
      %a{'data-toggle' => 'tab', href: '#process', role: 'tab'}
        Loan Process
    - third_active = (tab == 'faq') ? 'active' : 'not-active'
    %li{role: 'presentation', class: third_active}
      %a{'data-toggle' => 'tab', href: '#faq', role: 'tab'}
        FAQ
  .tab-content
    #programs.tab-pane.in.fade{class: first_active}
      = render partial: '/resources/loan_programs'
    #process.tab-pane.in.fade{class: second_active}
      = render partial: '/resources/loan_process'
    #faq.tab-pane.in.fade{class: third_active}
      = render partial: '/resources/loan_faq'