config/routes.rb
JasonHall::Application.routes.draw do
  resources :partners
  devise_for :admins

  root 'home#index'

  get "/reviews", to: 'review#index'
  get "/blog", to: 'blog#index'
  get "/resources", to: 'resources#index'
  get "/home", to: 'home#index'
  get "/blog/new"
  get "/blog/comments"
  get "/category", to: 'partners#category'
  get '/contact', to: 'contact#index'
  get '/tools', to: 'tools#index'
  get '/amortization_content', to: 'tools#amortization_content'

  post '/new_program', to: 'resources#new_program'
  post '/edit_program', to: 'resources#edit_program'
  post '/new_process', to: 'resources#new_process'
  post '/edit_process', to: 'resources#edit_process'
  post '/resources/swap', to: 'resources#swap'
  post '/new_question', to: 'resources#new_question'
  post '/edit_question', to: 'resources#edit_question'
  post '/resources/swap_question', to: 'resources#swap_question'
  post '/blog/approve'
  post '/blog/new_comment'
  post '/blog/new_post'
  post '/blog/edit'
  post '/blog/approve_comment'
  post '/blog/delete_comment'
  post '/blog/delete_post'
  post '/new_partner', to: 'partners#new_partner'
  post '/edit_partner', to: 'partners#edit_partner'
  post '/send_feedback', to: 'contact#send_feedback'
  post '/calculate_amortization', to: 'tools#calculate_amortization'
  post '/text_review', to: 'review#text_review'
  post '/video_review', to: 'review#video_review'
  post '/approve_text_review', to: 'review#approve_text_review'
  post '/remove_text_review', to: 'review#remove_text_review'
  post '/add_video', to: 'review#add_video'
  post '/delete_video', to: 'review#delete_video'
  post '/add_review', to: 'review#add_review'

  patch '/blog/edit_post/:id', to: 'blog#edit_post'

  delete '/delete_program', to: 'resources#delete_program'
  delete '/delete_process', to: 'resources#delete_process'
  delete '/delete_question', to: 'resources#delete_question'
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index
    @articles = {}
    @recent_posts = tumblr_client.posts(ENV['TUMBLR_BLOG'], limit: 30)['posts']
    @recent_posts.each do |external_post|
      post = Post.where(id: external_post['id']).first_or_initialize
      date = external_post['date'].to_datetime
      post.update_attributes!(title: external_post['title'], body: external_post['body'], post_date: date)
      id = post['id']
      title = post['title']
      key = date.strftime("%B %Y")
      if @articles.has_key? key
        @articles[key] << { id: id, title: title, date: date }
      else
        @articles[key] = [{ id: id, title: title, date: date }]
      end
    end
    post_id = params['post']
    @post = post_id.blank? ? Post.order('post_date').last : Post.find(post_id)
    @articles.each { |a, v| v.sort_by! { |hsh| hsh[:date] }}
    @articles = Hash[@articles.sort_by { |k, v| k.to_datetime }.reverse! ]
     feed = Feedjira::Feed.fetch_and_parse("http://davematthews.tumblr.com/rss")
    @entries = []
    feed.entries.each do |e|
      @entries << {title: e.title, content: e.summary.html_safe}
    end
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params['post'])
  end

  def edit_post
    blog_id = params['id']
    post = params['post']
    title = post['title']
    body = post['body']
    Post.find(blog_id).update_attributes!(title: title, body: body)
    tumblr_client.edit(ENV['TUMBLR_BLOG'], id: blog_id, title: title, body: body)
    redirect_to blog_index_path
  end

  def new_post
    post = params['post']
    title = post['title']
    body = post['body']
    post = tumblr_client.text(ENV['TUMBLR_BLOG'], title: title, body: body)
    Post.create!(id: post['id'], title: title, body: body)
    redirect_to blog_index_path
  end

  def delete_post
    post_id = params['post_id']
    result = tumblr_client.delete(ENV['TUMBLR_BLOG'], post_id)
    Post.find(post_id).destroy!
    redirect_to blog_index_path
  end

  def comments
    @comments = Post.find(params['post_id']).blog_comments.by_date
    render partial: '/blog/comments', locals: { comments: @comments }
  end

  def new_comment
    comment = params['comment']
    name = comment['name'].blank? ? 'Anonymous' : comment['name']
    id = comment['id']
    text = comment['comment']
    post = Post.find(comment['post_id'])
    comment = BlogComment.new
    comment.name = name
    comment.comment = text
    comment.status = 'pending'
    post.blog_comments << comment
    render partial: '/blog/comments', locals: { comments: post.blog_comments.by_date }
  end

  def approve_comment
    b = BlogComment.find(params['id'])
    b.status = 'approved'
    b.save
    render nothing: true
  end

  def delete_comment
    b = BlogComment.find(params['id'])
    b.destroy
    redirect_to blog_index_path
  end

  private

  def tumblr_client
    if @tumblr.blank?
      Tumblr.configure do |config|
        config.client = :HTTPClient
        config.consumer_key = ENV['TUMBLR_OAUTH_KEY']
        config.consumer_secret = ENV['TUMBLR_OAUTH_SECRET']
        config.oauth_token = ENV['TUMBLR_API_TOKEN']
        config.oauth_token_secret = ENV['TUMBLR_API_TOKEN_SECRET']
      end
      @tumblr = Tumblr::Client.new
    end
    @tumblr
  end
end

app/views/blog/_comments.html.haml
- if comments.present?
  - comments.each do |c|
    - next unless admin_signed_in? || c.status != 'pending'
    .main-comment-container
      .comment.accent-5
        .inner-comment
          %h5.accent-5
            = c.comment
          %em
            = "-#{c.name}"
      - if admin_signed_in?
        .blog-controls.pull-right{'data-comment-id' => c.id}
          - if c.status == 'pending'
            %a.approve-comment{href: '#'}
              = fa_icon 'check', class: 'white'
          %a.remove-comment{href: '#'}
            = fa_icon 'trash', class: 'white'
        .clearfix

app/views/blog/_post.html.haml
%h2.center{'data-post-id' => post['id']}
  = post['title']
%blockquote
  = post['body'].html_safe

app/views/blog/edit.html.haml
%h3.white.center Edit blog post
%hr
.post-container
  = form_for @post, url: {action: :edit_post, controller: :blog, id: @post.id}, html: {id: 'edit_post_form', class: "form form-horizontal"} do |f|
    .form-group
      .col-sm-2
        = f.label :title, class: 'control-label white'
      .col-sm-10
        = f.text_field :title, {class: 'form-control', required: true}
    .form-group
      .col-sm-2
        = f.label :body, class: 'control-label white'
      .col-sm-10
        = f.text_area :body, {id: 'edit_blog_editor', class: 'form-control edit-text-area tinymce full-width', required: true, rows: 20}
    .form-group
      .col-sm-offset-2.col-sm-10
        %button.btn.btn-default.pull-right{:type => "submit"} Submit
        = link_to 'Back', :back, class: 'btn btn-default pull-right back-button'

app/views/blog/index.html.haml
- if admin_signed_in?
  .add-blog-post.center
    = link_to blog_new_path, class: 'center complimentary' do
      = fa_icon "plus", text: "Add New Post"
.blog-content.container-fluid
  .row
    .archive-container.col-md-2
      .post-container
        - first = true
        - @articles.each do |month, posts|
          - date = month.gsub(' ', '').downcase
          - open = first ? 'in' : ''
          - caret = first ? 'fa-caret-down' : 'fa-caret-right'
          .panel-group.article-group{id: "accordion_#{date}"}
            .panel.panel-default.articles-panel{'data-toggle' => 'collapse', 'data-parent' => "accordion_#{date}", href: "#collapse#{date}"}
              %h4.blog-panel-title-panel-title
                %a.complimentary{'data-toggle' => 'collapse', 'data-parent' => "accordion_#{date}", href: "#collapse#{date}"}
                  = month
                %i.caret-toggle.fa{class: caret}
            .blog-panel-collapse.panel-collapse.collapse{id: "collapse#{date}", class: open}
              .panel-body
                %ul
                  - posts.each do |p|
                    %li
                      .post{'data-post-id' => p[:id]}
                        = link_to blog_path(post: p[:id]), class: 'complimentary' do
                          = p[:title]
    .col-md-7.white-back.blog-section.bottom-thirty
      .feed.scrollable.hidden-xs
        - if @entries.any?
          .text-center
            %span Live Feed
          - @entries.each do |e|
            %h5.white
              = e[:title]
            .content-section.white
              = e[:content]
            %hr
      .col-xs-12
        %hr
      .blog-container.white-back
      - if admin_signed_in?
        = link_to blog_edit_path(post: @post), method: :post, class: 'black' do
          = fa_icon 'pencil', text: 'Edit Post', class: 'black'
        = link_to blog_delete_post_path(post_id: @post['id']), method: :post, class: 'black pull-right' do
          = fa_icon 'trash', class: 'black'
      = render partial: 'post', locals: { post: @post }
    .comments-container.col-md-3
      %h4.complimentary.center Comments
      %hr
      %a#new_comment.white{href: '#'}
        = fa_icon 'plus', text: 'Add Comment', class: 'white'
      %form#new_comment_form.hidden{role: 'form', action: '/blog/new_comment', method: 'POST'}
        = hidden_field_tag :authenticity_token, form_authenticity_token
        = hidden_field_tag :post_id, @post.id
        .form-group
          %label.white{for: 'user_name'} Name:
          %input#user_name.form-control{type: 'text', name: 'name'}
        .form-group
          %label.white
            %input#anon.white{type: 'checkbox'} Post Anonymously?
        .form-group
          %label.white{for: 'user_comment'} Comment:
          %textarea#user_comment.form-control{rows: 3, name: 'comment'}
        %button.btn.gradient.full-width{type: 'submit'} Comment
      .comments

app/views/blog/new.html.haml
= tinymce
%h3.white.center Create new blog post
%hr
.post-container
  = form_for @post, url: {action: :new_post, controller: :blog}, html: {id: 'new_post_form', class: "form form-horizontal"} do |f|
    .form-group
      .col-sm-2
        = f.label :title, class: 'control-label white'
      .col-sm-10
        = f.text_field :title, {class: 'form-control', required: true}
    .form-group
      .col-sm-2
        = f.label :body, class: 'control-label white'
      .col-sm-10
        = f.text_area :body, {rows: 20, class: 'form-control tinymce full-width'}
    .form-group
      .col-sm-offset-2.col-sm-10
        %button#new_post_button.btn.btn-default.pull-right.font-l{type: 'submit'} Submit
        = link_to 'Back', :back, class: 'btn btn-default pull-right back-button'