config/routes.rb
JasonHall::Application.routes.draw do
  resources :partners
  devise_for :admins

  root 'home#index'

  get "/reviews", to: 'review#index'
  get "/blog", to: 'blog#index'
  get "/resources", to: 'resources#index'
  get "/home", to: 'home#index'
  get "/blog/new"
  get "/blog/comments"
  get "/category", to: 'partners#category'
  get '/contact', to: 'contact#index'
  get '/tools', to: 'tools#index'
  get '/amortization_content', to: 'tools#amortization_content'

  post '/new_program', to: 'resources#new_program'
  post '/edit_program', to: 'resources#edit_program'
  post '/new_process', to: 'resources#new_process'
  post '/edit_process', to: 'resources#edit_process'
  post '/resources/swap', to: 'resources#swap'
  post '/new_question', to: 'resources#new_question'
  post '/edit_question', to: 'resources#edit_question'
  post '/resources/swap_question', to: 'resources#swap_question'
  post '/blog/approve'
  post '/blog/new_comment'
  post '/blog/new_post'
  post '/blog/edit'
  post '/blog/approve_comment'
  post '/blog/delete_comment'
  post '/blog/delete_post'
  post '/new_partner', to: 'partners#new_partner'
  post '/edit_partner', to: 'partners#edit_partner'
  post '/send_feedback', to: 'contact#send_feedback'
  post '/calculate_amortization', to: 'tools#calculate_amortization'
  post '/text_review', to: 'review#text_review'
  post '/video_review', to: 'review#video_review'
  post '/approve_text_review', to: 'review#approve_text_review'
  post '/remove_text_review', to: 'review#remove_text_review'
  post '/add_video', to: 'review#add_video'
  post '/delete_video', to: 'review#delete_video'
  post '/add_review', to: 'review#add_review'

  patch '/blog/edit_post/:id', to: 'blog#edit_post'

  delete '/delete_program', to: 'resources#delete_program'
  delete '/delete_process', to: 'resources#delete_process'
  delete '/delete_question', to: 'resources#delete_question'
end

app/views/layouts/_add_review.html.haml
#add_reviews_modal.modal.fade
  .modal-dialog
    .modal-content
      .modal-body
        %h2 Add a review
        %form#quick_review_form{type: 'form', action: '/add_review', method: 'post'}
          = hidden_field_tag :authenticity_token, form_authenticity_token
          .form-group
            %label{for: 'user_name'} Name:
            %input#user_name.form-control{type: 'text', name: 'name'}
          .form-group
            %label{for: 'quick_review'} Review:
            %textarea#quick_review.form-control{rows: 3, name: 'review'}
          .modal-footer
            .pull-right
              %button.btn.btn-default{type: 'button', 'data-dismiss' => 'modal'} Close
              %button.btn.btn-primary{type: 'submit'} Submit

app/views/layouts/_add_video.html.haml
#add_videos_modal.modal.fade
  .modal-dialog
    .modal-content
      .modal-body
        %h2 Add a video
        %form#video_form{type: 'form', action: '/add_video', method: 'post'}
          = hidden_field_tag :authenticity_token, form_authenticity_token
          .form-group
            %input#video_url.form-control{name: 'url', placeholder: "youtube.com/id", type: 'text', 'required' => 'true'}
          .modal-footer
            .pull-right
              %button.btn.btn-default{type: 'button', 'data-dismiss' => 'modal'} Close
              %button.btn.btn-primary{type: 'submit'} Submit

app/views/layouts/_header.html.haml
.navbar.navbar-default{role: 'navigation'}
  .container-fluid
    .navbar-header
      %button.navbar-toggle.complimentary{"data-target" => "#nav-items", 'data-toggle' => 'collapse', type: 'button'}
        %span.sr-only Toggle Navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a#logo.pull-left{href: '/'}
        .shadow.forum.complimentary
          Jason Hall
        .sub-logo.shadow
          Home Loans
        .small-print NMLS# 297434
    .nav-header
      = render(partial: 'layouts/social_media_links', locals: {id: 'follow', classes: 'hidden-xs hidden-s'})
    .collapse.navbar-collapse#nav-items.navbar-right
      %ul.nav.navbar-nav
        %li
          = link_to("Home", '/', class: 'nav-item')
        %li
          = link_to("Blog", blog_path, class: 'nav-item')
        %li
          = link_to("Loan Resources", resources_path, class: 'nav-item')
        %li
          = link_to("Partners", partners_path, class: 'nav-item')
        %li
          = link_to("Tools", tools_path, class: 'nav-item')
        %li
          = link_to("Reviews", reviews_path, class: 'nav-item')
        %li
          = link_to(contact_path, class: 'nav-item') do
            = fa_icon "envelope"
        %li.dropdown
          %a.dropdown-toggle{'data-toggle' => 'dropdown', href: '#'}
            %b.fa.fa-gears
          %ul.dropdown-menu
            %li
              - if admin_signed_in?
                = link_to 'Logout', destroy_admin_session_path, method: :delete, class: 'delete'
              - else
                = link_to 'Sign In', new_admin_session_path, method: :get
        %li
          = render(partial: 'layouts/social_media_links', locals: {id: 'sm_links', classes: 'visible-xs visible-s'})
        %li
          %a#apply_button.btn.gradient{href: 'https://www.mysecureloan.com/5step/page1.php?custid=5255&office_id=1235&loan_officer=14929&b=5255', target: '_blank'}
            = fa_icon 'check', text: 'Apply Now'

app/views/layouts/_social_media_links.html.haml
%div{id: id, class: classes}
  = link_to "https://www.facebook.com/jasonhall", {target: '_blank'} do
    = fa_icon 'facebook', class: 'complimentary social-nav shadow'
  = link_to "https://www.youtube.com/", {target: '_blank'} do
    = fa_icon 'youtube', class: 'complimentary social-nav shadow'
  = link_to "https://www.tumblr.com", {target: '_blank'} do
    = fa_icon 'tumblr', class: 'complimentary social-nav shadow'
  = link_to "https://www.linkedin.com", {target: '_blank'} do
    = fa_icon 'linkedin', class: 'complimentary social-nav shadow'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title JasonHall
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %script{:src => "//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry", :type => "text/javascript"}
    %script{:src => "//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js", :type => "text/javascript"}
  %body
    #header
      = render :partial => "shared/bflash"
      = render :partial => "layouts/header"
    = yield
  %footer.footer
    #footer.container
      .footer-content
        .col-xs-2.col-xs-offset-1
          .text-center
            %h6.white NMLS# 297434
        .col-xs-2.col-xs-offset-2
          .text-center
            = image_tag 'umlc.png', class: 'company-logo'
        .col-xs-2.col-xs-offset-2
          .text-center
            %h6.white Company NMLS# 149160